FROM node:13.5.0-alpine as run-react

# set working directory
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH
ENV NODE_ENV development
ENV REACT_APP_USERS_SERVICE_URL $REACT_APP_USERS_SERVICE_URL
ENV REACT_APP_AUTH0_DOMAIN $REACT_APP_AUTH0_DOMAIN
ENV REACT_APP_API_AUDIENCE $REACT_APP_API_AUDIENCE
ENV REACT_APP_AUTH0_CLIENT_ID $REACT_APP_AUTH0_CLIENT_ID
ENV REACT_APP_DOMAIN $REACT_APP_DOMAIN

# install and cache app dependencies
COPY package.json /usr/src/app/package.json
COPY package-lock.json /usr/src/app/package-lock.json
RUN npm ci
RUN npm install react-scripts@3.3.0 -g --silent

# add app
COPY . /usr/src/app

# start app
CMD ["npm", "start"]

FROM cypress/browsers:chrome65-ff57

# set working directory
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH
ENV CI=1

# copy cypress files and folders
COPY --from=run-react /usr/src/app /usr/src/app

# install cypress
RUN npm install cypress

COPY cypress /usr/src/app/cypress
COPY cypress.json /usr/src/app/cypress.json

# confirm the cypress install
RUN ./node_modules/.bin/cypress verify